### ISSUE TITLE
Stack is not being emptied

### ISSUE THREAD

**Issue by Furetur** [Furetur/SimpleLanguage#1]
[test.txt](https://github.com/Furetur/SimpleLanguage/files/6360610/test.txt)

**Comment by EmirVildanov** [comment]
Agree!!! I have faced such bug recently! If you find how to fix it, please tag me.

**Comment by Furetur** [comment]
Bro, I feel you. Will text once I get it fixed [̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]

**Comment by Furetur** [comment]
@EmirVildanov I identified where the bug is my dude, ima fix it ASAP

**Comment by Furetur** [comment]
@EmirVildanov  _***bro***_ the bug is now FIIIIIIIIIIXED!!!!!! You can check out how it works now on this example:

[emir.txt](https://github.com/Furetur/SimpleLanguage/files/6369029/emir.txt)
